name: cicd
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: clone the repository
        uses: actions/checkout@v4.1.5
      - name: list files
        run: ls -l
      - name: Isntalling Java 11 on the runner machine
        uses: action/setup-java@4.2.1
        with:
          java-version : "11"
          cache: "mavan"
      - name: verify java
        run: java -version
